### ISSUE TITLE
Ability to pause during the ride

### ISSUE THREAD

**Issue by AntoineTurmel** [nicodel/Run-Bike-Hike#37]
I was using RunKeeper and there was a pause button, useful when you want to walk between two foot race.
Is it possible to add a pause button in Run-Bike-Hike ? :)

**Comment by AntoineTurmel** [comment]
J'ai testé l'application hier soir lors d'un footing.
J'ai fait un test en effectuant un premier tracé, en marchant et en mettant en pause plusieurs fois.
Puis tracé en courant avec plusieurs pauses.

Une fois importé dans [Runkeeper](http://runkeeper.com/), le trajet de marche n'affiche aucune pause, et celui où je cours une seule pause (alors que pour les 2 tracés j'en ai fait au moins 5...)

Trajet de marche :
GPX : http://cloud.turmel.info/public.php?service=files&t=6bf8da781a991eb6ba6d6a4592c199a7
![1](https://cloud.githubusercontent.com/assets/119288/6374301/4a41e102-bd10-11e4-9151-4b898da90979.png)

Trajet en courant :
GPX : http://cloud.turmel.info/public.php?service=files&t=3494f2eaaa0add28b6bfe1c8715ff70f
![2](https://cloud.githubusercontent.com/assets/119288/6374309/517dfc80-bd10-11e4-8c77-a7a6be8dfccf.png)

Pour référence, voici un tracé généré avec l'application Runkeeper qui date d'Avril 2014 :
GPX : http://cloud.turmel.info/public.php?service=files&t=20ae6b57b823a86579bc976d515a0920
![3](https://cloud.githubusercontent.com/assets/119288/6374393/e4c7daec-bd10-11e4-9114-71f818b49d0b.png)
(où l'on voit bien les 3 pauses en course)

**Comment by AntoineTurmel** [comment]
En fait il faut créer un nouveau segment après une pause...
avec la balise <trkseg>

**Comment by nicodel** [comment]
Merci pour ces informations !

**Comment by nicodel** [comment]
v0.1.15 now support multi-segment

**Comment by AntoineTurmel** [comment]
Nice ! I'll try when I can :)
