### ISSUE TITLE
Frequency of adding new point should follow the positioning frequency's setting.

### ISSUE THREAD

**Issue by Bonbadil** [nicodel/Run-Bike-Hike#75]
Hello,
A setting had been added to let the user choose the frequency of awakening the GPS chip. But the app still continuously add new point, even if no new positioning data is produced by the GPS. This point between two geolocalisations seem useless to me. For example, on my phone, I store 2 track's points by second, even with a positioning period set at 10 seconds.
Why watchPosition still calling success callback so often if we set maximumAge to several seconds?

**Comment by nicodel** [comment]
I got a look at the specs, and it depends on the device. If the device actually supports cache position, this should work. If not...
